version: '2'
services:
  management-admin:
    image: management/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  management-api:
    image: management/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev